import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packages = ["core", "cli", "plugin", "viewer"];

for (const pkgName of packages) {
  const pkgPath = join(root, "packages", pkgName, "package.json");
  const outPath = join(root, "packages", pkgName, "src", "version.ts");

  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  const content =
    `// Auto-generated by scripts/sync-version.mjs. Do not edit by hand.\n` +
    `export const VERSION: string = ${JSON.stringify(pkg.version)};\n`;

  writeFileSync(outPath, content);
}

console.log(`[sync-version] wrote ${packages.length} files`);
